import Footer from "@/component/element/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Head from "next/head";
import GoogleAuth from "@/component/Authorization/GoogleAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Google Search",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="https://freepngimg.com/download/google/67060-play-photos-search-google-account-png-file-hd.png"
        type="image/png"
        sizes="32x32"
      />
      <body className={inter.className}>
        <GoogleAuth>
          {children}
          <Footer />
          <Toaster position="bottom-right" reverseOrder={false} />
        </GoogleAuth>
      </body>
    </html>
  );
}
